sources:
  # Programmatic / Custom Endpoints
  - name: eavor
    type: api
  - name: seeq
    type: api
  - name: black_veatch
    type: playwright
    urls:
      - "https://careers.bv.com/search/?createNewAlert=false&q=project+manager&locationsearch=canada+OR+united+states&optionsFacetsDD_customfield3=&optionsFacetsDD_customfield5=Project+Management"
      - "https://careers.bv.com/search/?createNewAlert=false&q=project+manager&locationsearch=canada&optionsFacetsDD_customfield3=&optionsFacetsDD_customfield5="
  - name: kanin_energy
    type: api
  - name: city_of_calgary
    type: taleo

  # Playwright Rendered Boards
  - name: cdr_jobs
    type: playwright
    url: "https://www.cdrjobs.earth/job-board"
  - name: climate_tech_list
    type: playwright
    url: "https://www.climatetechlist.com/jobs?location=calgary"
